//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string Comment { get; set; }
        public byte[] DateTime { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
