//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Favorities = new HashSet<Favority>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int VehicleID { get; set; }
        public string VehicleName { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public string AvailabilityStatus { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> VehicleCategoryID { get; set; }
        public Nullable<int> VehicleBrandID { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<int> Status { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> VehicleUserID { get; set; }
        public string Color { get; set; }
        public string RegistrationNumber { get; set; }
        public string Transmission { get; set; }
        public string Owner { get; set; }
        public string Description { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public string Address { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favority> Favorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual User User { get; set; }
    }
}
