//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public string VehicleName { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public string AvailabilityStatus { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> VehicleCategoryID { get; set; }
        public Nullable<int> VehicleBrandID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
